version: "3.2"
services:
  db:
      image: postgres
      ports:
      - "5435:5432"
      environment:
        POSTGRES_USER: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: orders_service_dev
  app:
    command: npm start
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4001:${PORT}
    volumes:
      - .:/app/
    environment:
      DATABASE_DEV_URL: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db:5432/orders_service_dev